name: Template Run PowerShell Script e213ff0f-5d5c-4791-802d-52ea3e7be1f1

on:
  workflow_call:
    inputs:
      targetType:
        required: true
        type: string
        description: "'inlineScript' or 'filePath'"
      filePath:
        required: false
        type: string
        description: "Path to the script file (required if targetType is 'filePath')"
      arguments:
        required: false
        type: string
        description: "Arguments to pass to the script"
      script:
        required: false
        type: string
        description: "Inline PowerShell script (required if targetType is 'inlineScript')"
      workingDirectory:
        required: false
        type: string
        description: "Working directory"
      errorPreference:
        required: false
        type: string
        default: Stop
        description: "Error preference (Stop or Continue)"
      ignoreLASTEXITCODE:
        required: false
        type: boolean
        default: false
        description: "Ignore the last exit code"
      warningPreference:
        required: false
        type: string
        default: SilentlyContinue
        description: "'SilentlyContinue' | 'Stop' | 'Continue' | 'Inquire' | 'Ignore' | 'Suspend' | 'Break'. WarningPreference."
      informationPreference:
        required: false
        type: string
        default: SilentlyContinue
        description: "'SilentlyContinue' | 'Stop' | 'Continue' | 'Inquire' | 'Ignore' | 'Suspend' | 'Break'. InformationPreference."
      verbosePreference:
        required: false
        type: string
        default: SilentlyContinue
        description: "'SilentlyContinue' | 'Stop' | 'Continue' | 'Inquire' | 'Ignore' | 'Suspend' | 'Break'. VerbosePreference."
      debugPreference:
        required: false
        type: string
        default: SilentlyContinue
        description: "'SilentlyContinue' | 'Stop' | 'Continue' | 'Inquire' | 'Ignore' | 'Suspend' | 'Break'. DebugPreference."
      progressPreference:
        required: false
        type: string
        default: SilentlyContinue
        description: "'SilentlyContinue' | 'Stop' | 'Continue' | 'Inquire' | 'Ignore' | 'Suspend' | 'Break'. ProgressPreference."
      failOnStderr:
        required: false
        type: boolean
        default: false
        description: "Fail on Standard Error. Default: false."
      showWarnings:
        required: false
        type: boolean
        default: false
        description: "Show warnings as Azure DevOps warnings. Default: false."
      runScriptInSeparateScope:
        required: false
        type: boolean
        default: false
        description: "Run script in a separate scope. Default: false."

jobs:
  powershell-task:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          # Set preferences
          $ErrorActionPreference = '${{ inputs.errorPreference }}'
          $WarningPreference = if ('${{ inputs.warningPreference }}' -eq 'default') { 'SilentlyContinue' } else { '${{ inputs.warningPreference }}' }
          $InformationPreference = if ('${{ inputs.informationPreference }}' -eq 'default') { 'SilentlyContinue' } else { '${{ inputs.informationPreference }}' }
          $VerbosePreference = if ('${{ inputs.verbosePreference }}' -eq 'default') { 'SilentlyContinue' } else { '${{ inputs.verbosePreference }}' }
          $DebugPreference = if ('${{ inputs.debugPreference }}' -eq 'default') { 'SilentlyContinue' } else { '${{ inputs.debugPreference }}' }
          $ProgressPreference = if ('${{ inputs.progressPreference }}' -eq 'default') { 'SilentlyContinue' } else { '${{ inputs.progressPreference }}' }
          $ignoreLASTEXITCODE = ${{ inputs.ignoreLASTEXITCODE }}
          $failOnStderr = ${{ inputs.failOnStderr }}
          $showWarnings = ${{ inputs.showWarnings }}
          $runScriptInSeparateScope = ${{ inputs.runScriptInSeparateScope }}

          # Resolve working directory and verify its existence
          $workingDirectory = if ('${{ inputs.workingDirectory }}' -ne '') { '${{ inputs.workingDirectory }}' } else { '.' }
          if (!(Test-Path -Path $workingDirectory)) {
            Write-Error "Working directory does not exist: $workingDirectory"
            exit 1
          }
          Set-Location -Path $workingDirectory

          # Execute the script based on targetType
          if ('${{ inputs.targetType }}' -eq 'inlineScript') {
            Write-Host "Running inline script..."
            try {
              Invoke-Expression "${{ inputs.script }}"
            } catch {
              if ($ErrorActionPreference -eq 'Stop') {
                Write-Error "Inline script execution failed with error: $_"
                exit 1
              } else {
                Write-Warning "Inline script execution encountered an error: $_"
              }
            }
          } elseif ('${{ inputs.targetType }}' -eq 'filePath') {
            Write-Host "Running script from file path..."
            $scriptPath = "${{ inputs.filePath }}"
            if (Test-Path $scriptPath) {
              try {
                & $scriptPath ${{ inputs.arguments }}
                if (-not $ignoreLASTEXITCODE -and $LASTEXITCODE -ne 0) {
                  if ($ErrorActionPreference -eq 'Stop') {
                    Write-Error "Script exited with a non-zero exit code: $LASTEXITCODE"
                    exit $LASTEXITCODE
                  } else {
                    Write-Warning "Script exited with a non-zero exit code: $LASTEXITCODE"
                  }
                }
              } catch {
                if ($ErrorActionPreference -eq 'Stop') {
                  Write-Error "Script execution failed with error: $_"
                  exit 1
                } else {
                  Write-Warning "Script execution encountered an error: $_"
                }
              }
            } else {
              Write-Error "Script file not found: $scriptPath"
              exit 1
            }
          } else {
            Write-Error "Invalid targetType provided: '${{ inputs.targetType }}'"
            exit 1
          }
